apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- arc-healthcheck-patch.yaml
- job-cleaner-patch.yaml
- machineset-patch.yaml
- sealed-secrets-patch.yaml
- metallb-patch.yaml
- delete-unneeded-apps.yaml