apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- configs/azure-spn-secret.yaml

# KangarooKube/kube-arc-data-services-installer-job assumes ConfigMap and Secrets will be passed in via env variables.
# This is a problem in ArgoCD since there is no env variable.

# ConfigMap: overwrite the existing Configmap with literals since these are non-secret anyway
configMapGenerator:
- name: config-envs
  behavior: replace
  namespace: azure-arc-kubernetes-bootstrap
  envs:
  - configs/configMap.env
- name: dc-config
  behavior: replace
  namespace: azure-arc-kubernetes-bootstrap
  files:
    - configs/control.json

# Secret: making this work with Sealed Secrets
# https://github.com/kubernetes-sigs/kustomize/blob/master/examples/transformerconfigs/README.md#example
configurations:
  - configs/sealed-secret-config.yaml

# Empty secret that will be overwritten by Sealed Secret above
secretGenerator:
- name: secret-envs
  behavior: replace
  type: Opaque
  namespace: azure-arc-kubernetes-bootstrap

# Necessary for sealed Secrets to manage the generated Secret
# https://github.com/kubernetes-sigs/kustomize/blob/master/examples/generatorOptions.md <- One Option, adds it to all Secrets and ConfigMaps
# https://github.com/kubernetes-sigs/kustomize/issues/2179#issuecomment-582562891
# https://fabianlee.org/2022/04/15/kubernetes-kustomize-transformations-with-patchesjson6902/
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/ <- Best option, used below
patches:
  - patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: secret-envs
        annotations:
          sealedsecrets.bitnami.com/managed: "true"
          sealedsecrets.bitnami.com/namespace-wide: "true"
    target:
      version: v1
      kind: Secret
      name: secret-envs
      namespace: azure-arc-kubernetes-bootstrap

  # https://github.com/argoproj/argo-cd/discussions/8555
  # To get the job to rerun without messing around with CLI, we change this DELETE_FLAG annotation to be the same value as the ConfigMap
  # Changing this annotation only triggers a job rerun, the actual behaviour is still driven by the ConfigMap
  - patch: |-
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: azure-arc-kubernetes-bootstrap
        annotations:
          DELETE_FLAG: "false"
    target:
      version: batch/v1
      kind: Job
      name: azure-arc-kubernetes-bootstrap
      namespace: azure-arc-kubernetes-bootstrap