apiVersion: metallb.io/v1alpha1
kind: AddressPool
metadata:
  name: metallb-addresspool
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  protocol: layer2
  autoAssign: true
  addresses:
  - 0.0.0.0-255.255.255.0