apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: job-cleaner
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '-1' # No dependencies
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: job-cleaner
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ${unique-path-per-overlay}
    repoURL: 'https://github.com/mdrakiburrahman/openshift-app-of-apps.git'
    targetRevision: HEAD