apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - arc-healthcheck.yaml
  - machineset.yaml
  - sealed-secrets.yaml
  - metallb.yaml
  # - arc-data-services-onboard.yaml
  # - sql-gp-ad-1.yaml