apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: machineset
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@github.com:mdrakiburrahman/openshift-app-of-apps.git
    path: ${unique-path-per-overlay}
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-machine-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=false # Already exists
