apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '5'
  name: sql-gp-ad-1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/mdrakiburrahman/openshift-app-of-apps.git'
    path: ${unique-path-per-overlay}
    targetRevision: HEAD
    directory: # testing
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: azure-arc-data
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=false # azure-arc-data already exists