apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '4'
  name: sql-bc-ad-1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/mdrakiburrahman/openshift-app-of-apps.git'
    path: ${unique-path-per-overlay}
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: azure-arc-data
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      selfHeal: true
    syncOptions:
      - CreateNamespace=false # azure-arc-data already exists
      - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).