apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- role-anyuid-patch.yaml # Needed for OpenShift SCCs

# Update RBAC GVK to v1beta1
patches:
- patch: |-
    - op: replace
      path: "/apiVersion"
      value: rbac.authorization.k8s.io/v1
  target:
    group: rbac.authorization.k8s.io
    version: v1beta1