apiVersion: v1
data:
  password: YWNudG9yUFJFU1RPIQ==
  username: Ym9vcg==
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: sql-gp-ad-1-secret
  namespace: azure-arc-data
type: Opaque
---
apiVersion: sql.arcdata.microsoft.com/v5
kind: SqlManagedInstance
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: sql-gp-ad-1
  namespace: azure-arc-data
spec:
  backup:
    retentionPeriodInDays: 7
  dev: true
  forceHA: "true"
  licenseType: LicenseIncluded
  replicas: 1
  scheduling:
    default:
      resources:
        limits:
          cpu: "2"
          memory: 4Gi
        requests:
          cpu: "1"
          memory: 2Gi
  security:
    activeDirectory:
      accountName: sql-gp-ad-1-account
      connector:
        name: adarc
    adminLoginSecret: sql-gp-ad-1-secret
  services:
    primary:
      dnsName: sql-gp-ad-1.fg.contoso.com
      port: 31433
      type: LoadBalancer
  settings:
    network:
      forceencryption: "0"
      tlsprotocols: "1.2"
    sqlagent:
      enabled: "true"
  storage:
    data:
      volumes:
      - className: thin-csi
        size: 5Gi
    datalogs:
      volumes:
      - className: thin-csi
        size: 5Gi
    logs:
      volumes:
      - className: thin-csi
        size: 5Gi
  tier: GeneralPurpose
