# $patch: delete
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: kube-arc-data-services-installer-job
#   namespace: argocd
# ---
# $patch: delete
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: arc-active-directory-connector
#   namespace: argocd
# ---
$patch: delete
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sql-gp-ad-1
  namespace: argocd
---
$patch: delete
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sql-bc-ad-1
  namespace: argocd