apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- machineset-patch.yaml
- metallb-patch.yaml
- sealed-secrets-patch.yaml
- kube-arc-data-services-installer-job-patch.yaml
# - arc-active-directory-connector-patch.yaml