apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- arc-healthcheck-patch.yaml
- machineset-patch.yaml
- sealed-secrets-patch.yaml
- metallb-patch.yaml
- arc-data-services-onboard-patch.yaml
- sql-gp-ad-1-patch.yaml