apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: azure-arc-kubernetes-bootstrap

# Points to the repo so we are not duplicating YAML
bases:
- git::https://github.com/KangarooKube/kube-arc-data-services-installer-job.git//kustomize/overlays/ocp?ref=v0.0.1