apiVersion: arcdata.microsoft.com/v1beta2
kind: ActiveDirectoryConnector
metadata:
  name: adarc
  namespace: azure-arc-data
  annotations:
    argocd.argoproj.io/sync-wave: "4" # ADC comes up at the very end
spec:
  activeDirectory:
    realm: SUBDOMAIN.DOMAIN.COM
    netbiosDomainName: SUBDOMAIN
    serviceAccountProvisioning: automatic
    ouDistinguishedName: "OU=A,OU=B,DC=SUBDOMAIN,DC=DOMAIN,DC=COM"
    domainServiceAccountSecret: adarc-dsa-secret
    domainControllers:
      primaryDomainController:
        hostname: dc1.subdomain.domain.com
      secondaryDomainControllers:
      - hostname: dc2.subdomain.domain.com
  dns:
    preferK8sDnsForPtrLookups: false
    nameserverIPAddresses:
      - 0.0.0.0