apiVersion: v1 
kind: Secret 
type: Opaque 
metadata: 
  name: adarc-dsa-secret
  namespace: azure-arc-data
  annotations:
    argocd.argoproj.io/sync-wave: "3" # To only come up after the Job is completed, meaning the namespace exists
data: 
  password: <base64-encoded-domain-service-accnt-password>
  username: <base64-encoded-domain-service-accnt-username>