apiVersion: v1 
kind: Secret 
type: Opaque 
metadata: 
  name: adarc-dsa-secret
  namespace: azure-arc-data
data: 
  password: <base64-encoded-domain-service-accnt-password>
  username: <base64-encoded-domain-service-accnt-username>