apiVersion: v1 
kind: Secret 
type: Opaque 
metadata: 
  name: sql-gp-ad-1-secret
  namespace: azure-arc-data
data: 
  # Make sure this doesn't contain newline
  # Proper way
  # echo -n "acntorPRESTO!" | base64 -w 0
  password: YWNudG9yUFJFU1RPIQ==
  # echo -n "boor" | base64 -w 0
  username: Ym9vcg==