apiVersion: batch/v1
kind: Job
metadata:
  name: job-presync-hook
  annotations:
    argocd.argoproj.io/hook: PreSync # A preSync job, to run before anything else
spec:
  template:
    spec:
      containers:
        - name: job
          image: nginxinc/nginx-unprivileged
          command: ["sleep", "3"]
      restartPolicy: Never
---
apiVersion: v1 
kind: Secret 
type: Opaque 
metadata: 
  name: regular-secret # A regular secret that comes up with my main Job, would be good if this contributed to app health
data: 
  password: aGVsbG8K
  username: aGVsbG8K
---
apiVersion: batch/v1
kind: Job
metadata:
  name: regular-job-no-hook # just a regular job, I want my app health to depend on this
spec:
  template:
    spec:
      containers:
        - name: job
          image: nginxinc/nginx-unprivileged
          command: ["sleep", "10"]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-sync-hook
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1" # A "sync" job that should run after my regular-job-no-hook (default wave 0)
spec:
  template:
    spec:
      containers:
        - name: job
          image: nginxinc/nginx-unprivileged
          command: ["sleep", "5"]
      restartPolicy: Never
  backoffLimit: 0
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-postsync-hook-n-1
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "2" # The n-1 thing that should run
spec:
  template:
    spec:
      containers:
        - name: job
          image: nginxinc/nginx-unprivileged
          command: ["sleep", "2"]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-postsync-hook-n
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "3" # The n-1 thing that should run
spec:
  template:
    spec:
      containers:
        - name: job
          image: nginxinc/nginx-unprivileged
          command: ["sleep", "2"]
      restartPolicy: Never