apiVersion: v1 
kind: Secret 
type: Opaque 
metadata: 
  name: regular-secret # A regular secret that comes up with my main Job, would be good if this contributed to app health
data: 
  password: aGVsbG8K
  username: aGVsbG8K
---
apiVersion: batch/v1
kind: Job
metadata:
  name: regular-job-no-hook # just a regular job, I want my app health to depend on this
spec:
  template:
    spec:
      containers:
        - name: job
          image: nginxinc/nginx-unprivileged
          command: ["sleep", "3"]
      restartPolicy: Never