apiVersion: v1 
kind: Secret 
type: Opaque 
metadata: 
  name: adarc-dsa-secret
  namespace: azure-arc-data
  annotations:
    argocd.argoproj.io/sync-wave: "3" # To only come up after the Job is completed, meaning the namespace exists
data: 
  # Make sure this doesn't contain newline
  # Proper way
  # echo -n "acntorPRESTO!" | base64 -w 0
  password: YWNudG9yUFJFU1RPIQ==
  # echo -n "arcadc-sa" | base64 -w 0
  username: YXJjYWRjLXNh