apiVersion: v1 
kind: Secret 
type: Opaque 
metadata: 
  name: sql-bc-ad-1-secret
  namespace: azure-arc-data
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data: 
  password: <base64-encoded-domain-service-accnt-password>
  username: <base64-encoded-domain-service-accnt-username>