apiVersion: v1
kind: Namespace
metadata:
  name: single-job-hook-no
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-5"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-delete-sa
  namespace: single-job-hook-no
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-4"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-delete-role
  namespace: single-job-hook-no
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-3"
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-delete-rolebinding
  namespace: single-job-hook-no
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"
subjects:
- kind: ServiceAccount
  name: job-delete-sa
  namespace: single-job-hook-no
roleRef:
  kind: Role
  name: job-delete-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-delete-job
  namespace: single-job-hook-no
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "-1"
spec:
  template:
    spec:
      serviceAccountName: job-delete-sa
      restartPolicy: Never
      containers:
        - name: job-deleter-kubectl
          image: registry.redhat.io/openshift4/ose-cli
          command:
            - /bin/kubectl
            - get 
            - job
            - -n
            - single-job-hook-no

command:
 - /bin/sh
 - -c
 - counter=0; while [ $counter -lt 3 ]; do
counter=$((counter+1)); \
 echo "$counter"; sleep 3; done;
