apiVersion: arcdata.microsoft.com/v1beta2
kind: ActiveDirectoryConnector
metadata:
  name: adarc
  namespace: azure-arc-data
spec:
  activeDirectory:
    realm: FG.CONTOSO.COM
    netbiosDomainName: FG
    # fg, contoso, com -> needs to be lowercase due to mutatingwebhook "endswith" validation bug
    ouDistinguishedName: "OU=SQL MIs,OU=Arc CI,DC=fg,DC=contoso,DC=com"
    domainControllers:
      primaryDomainController:
        hostname: ocplab-dc1.fg.contoso.com
      secondaryDomainControllers:
      - hostname: ocplab-dc2.fg.contoso.com
  dns:
    nameserverIPAddresses:
      - 10.216.175.4
      - 10.216.175.5