apiVersion: arcdata.microsoft.com/v1beta2
kind: ActiveDirectoryConnector
metadata:
  name: adarc
  namespace: azure-arc-data
spec:
  activeDirectory:
    realm: fg.contoso.com
    netbiosDomainName: fg
    ouDistinguishedName: "OU=SQL MIs,OU=Arc CI,DC=fg,DC=contoso,DC=com" # Needs to be lowercase due to mutatingwebhook bug
    domainControllers:
      primaryDomainController:
        hostname: OCPLab-DC1.fg.contoso.com
  dns:
    nameserverIPAddresses:
      - 10.216.175.4