apiVersion: v1 
kind: Secret 
type: Opaque 
metadata: 
  name: adarc-dsa-secret
  namespace: azure-arc-data
data: 
  # Make sure this doesn't contain newline
  # Proper way
  # echo -n "acntorPRESTO!" | base64 -w 0
  password: YWNudG9yUFJFU1RPIQ==
  # echo -n "arcadc-sa" | base64 -w 0
  username: YXJjYWRjLXNh