apiVersion: v1 
kind: Secret 
type: Opaque 
metadata: 
  name: adarc-dsa-secret
  namespace: azure-arc-data
data: 
  # Make sure this doesn't contain newline
  # Proper way
  # echo -n "simplepassword" | base64 -w 0
  password: c2ltcGxlcGFzc3dvcmQ=
  # echo -n "arcadc-sa" | base64 -w 0
  username: YXJjYWRjLXNh