apiVersion: batch/v1
kind: Job
metadata:
  name: azure-arc-kubernetes-bootstrap
  namespace: azure-arc-kubernetes-bootstrap
  annotations:
    argocd.argoproj.io/sync-wave: "2" # So the job runs after all the pre-reqs are created