apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# OpenShift specific patches to Job
patchesStrategicMerge:
 - job-patch.yaml

# Image tag corresponding to Arc release train: https://github.com/KangarooKube/kube-arc-data-services-installer-job/pkgs/container/kube-arc-data-services-installer-job
images:
- name: kube-arc-data-services-installer-job
  newName: ghcr.io/kangarookube/kube-arc-data-services-installer-job
  newTag: v1.9.0_2022-07-12_preview

# ConfigMap: non-secrets, env specific
configMapGenerator:
- name: config-envs
  namespace: azure-arc-kubernetes-bootstrap
  envs:
  - configs/configMap.env
- name: dc-config
  namespace: azure-arc-kubernetes-bootstrap
  files:
    - configs/control.json
- name: openshift-config
  namespace: azure-arc-kubernetes-bootstrap
  files:
    - configs/arc-data-routes.yaml
    - configs/arc-data-scc.yaml